# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-04 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('submit_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SubmitAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='')),
                ('submit_date', models.DateField()),
                ('grad', models.CharField(choices=[('a+', 'A+'), ('a', 'A'), ('b+', 'B+'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=50)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CreateAssignment')),
                ('submit_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
