# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-05 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createassignment',
            name='submit_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submitassignment',
            name='grad',
            field=models.CharField(choices=[('a+', 'A+'), ('a', 'A'), ('b+', 'B+'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=50, null=True),
        ),
    ]
