# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-05 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180105_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitassignment',
            name='submit_date',
            field=models.DateField(null=True),
        ),
    ]
